src/MvdEndPoint.UI/Models/IncAjaxEventVm.cs
namespace MvdEndPoint.UI.Models
{
    public class IncAjaxEventVm
    {
        #region Properties

        public string ResponseText { get; set; }

        public string StatusCode { get; set; }

        public string StatusText { get; set; }

        #endregion
    }
}

src/MvdEndPoint.UI/Controllers/DispatcherController.cs
namespace MvdEndPoint.UI.Controllers
{
    using System.Web.Mvc;
    using Incoding.MvcContrib.MVD;

    [ValidateInput(false)]
    public class DispatcherController : DispatcherControllerBase
    {        
    }
}   

src/MvdEndPoint.UI/Controllers/EndpointController.cs
namespace MvdEndPoint.UI.Controllers
{
    #region << Using >>

    using System.Web.Mvc;
    using Incoding.CQRS;
    using Incoding.Endpoint;
    using Incoding.MvcContrib;

    #endregion

    public class EndpointController : IncControllerBase
    {
        public ActionResult Index()
        {
            dispatcher.Push(new SyncEndpointCommand());
            return View();
        }
    }
}

src/MvdEndPoint.UI/Controllers/HomeController.cs
namespace MvdEndPoint.UI.Controllers
{
    using System.Web.Mvc;    
    using Incoding.MvcContrib;

    public class HomeController : IncControllerBase
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/MvdEndPoint.UI/Views/Endpoint/Index.cshtml
@using System.Data
@using Incoding.CQRS
@using Incoding.Extensions
<html>
<head>
    <link rel="stylesheet" href="@Url.Content("~/Content/bootstrap.css")"/>
    <link rel="stylesheet" href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")"/>
    <link rel="stylesheet" href="@Url.Content("~/Content/endpoint.css")"/>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.10.0.js")"> </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui-1.10.4.min.js")"> </script>
    
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.history.js")"> </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/underscore.min.js")"> </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.form.min.js")"> </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.min.js")"> </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"> </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/handlebars.min.js")"> </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/incoding.framework.js")"> </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/incoding.meta.language.contrib.js")"> </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/endpoint.js")"></script>    
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>


    <script src="@Url.Content("~/Content/Trumbowyg-master/dist/trumbowyg.min.js")"></script>
    <link rel="stylesheet" href="@Url.Content("~/Content/Trumbowyg-master/dist/ui/trumbowyg.min.css")">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/styles/androidstudio.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/highlight.min.js"></script>

    <script>
        TemplateFactory.Version = '@Guid.NewGuid().ToString()';
    </script>
</head>

<body id="api-reference">

@Html.Incoding().RenderDropDownTemplate()
<div id="header">
    <div class="header-section header-section-sidebar text-center">
        <span class="switch-text">Editable mode </span>
        <div class="switch-inline">
            <label>
                @(Html.When(JqueryBind.Change)
                      .OnSuccess(dsl =>
                                 {
                                     dsl.WithClass("glyphicon-pushpin")
                                        .Behaviors(instancesDsl =>
                                                   {
                                                       instancesDsl.JQuery.Attr.AddClass(B.Hidden);
                                                       instancesDsl.JQuery.Attr.RemoveClass(B.Hidden).If(() => Selector.Jquery.Self());
                                                   });

                                     dsl.WithClass("ce-element").JQuery.Attr.ToggleClass(B.Active);
                                 })
                      .AsHtmlAttributes()
                      .ToInput(HtmlInputType.CheckBox, ""))
                <span>YES<i></i>NO</span>
            </label>
        </div>
    </div>
    <div class="header-section header-section-example">
        <div id="language">
            <ul class="language-toggle">
                @foreach (var type in new[] { "http", "curl", "android", "xamarin", "sandbox" })
                {
                    var attr = new RouteValueDictionary(new { @class = "language-toggle-source", name = "language-toggle" });
                    if (type == "android")
                    {
                        attr.Add(HtmlAttribute.Checked.ToStringLower(), HtmlAttribute.Checked);
                    }
                    <li>
                        @(Html.When(JqueryBind.Change)
                              .OnSuccess(dsl =>
                                         {
                                             dsl.WithClass("method-example").JQuery.Attr.AddClass(B.Hidden);
                                             dsl.WithClass(type).JQuery.Attr.RemoveClass(B.Hidden);
                                             dsl.Self().Eval("document.location = document.location").If(() => !Selector.JS.Location.Hash.IsEmpty());
                                         })
                              .AsHtmlAttributes(attr)
                              .ToInput(HtmlInputType.Radio, type))
                        <label class="language-toggle-button">@type</label>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>
@{
    var data = Html.Dispatcher().Query(new GetMessagesQuery(),new MessageExecuteSetting()
                                                              {
                                                                      IsolationLevel = IsolationLevel.ReadUncommitted,
                                                                      DataBaseInstance = "Endpoint"
                                                              });
    var pathToNavTmpl = "~/Views/Endpoint/Nav_Tmpl.cshtml";
}
<div id="sidebar">
    <nav role="navigation" class="sidebar-nav">
        @(Html.When(JqueryBind.None)
              .Ajax(new GetMessagesQuery.AsNav())
              .OnSuccess(dsl => dsl.Self().JQuery.Dom.WithTemplateByView(pathToNavTmpl).Html())
              .AsHtmlAttributes(new { @class = "sidebar-nav-items loaded", id = typeof(GetMessagesQuery.AsNav).Name })
              .ToTag(HtmlTag.Ul,@<text>
                                    @Html.Dispatcher().Query(new GetMessagesQuery.AsNav()).AsView(pathToNavTmpl)
                                 </text>))
    </nav>
</div>
<div id="background">
    <div class="background-actual"></div>
</div>
<div id="content">
    @data.AsView("~/Views/Endpoint/Item_Tmpl.cshtml")
</div>
</body>

</html>

src/MvdEndPoint.UI/Views/Endpoint/Nav_Tmpl.cshtml
@using System.Linq.Expressions
@helper Link(string name, string value, string @class)
{
    @(Html.When(JqueryBind.InitIncoding)
          .OnBegin(dsl => dsl.Break.If(() => value == ""))
          .OnSuccess(dsl =>
          {

              Expression<Func<bool>> isSelf = () => Selector.JS.Location.Hash == "#" + value;
              dsl.Self().JQuery.Attr.AddClass(B.Active).If(isSelf);
              dsl.Self().JQuery.Attr.AddClass(B.Active).If(() => Selector.JS.Location.Hash.IsEmpty() && Selector.Jquery.Class(B.Active).Length() == 0);
              dsl.Self().Eval("document.location = document.location").If(isSelf);
          })
          .When(JqueryBind.Click)
          .OnSuccess(dsl =>
          {
              dsl.WithClass(B.Active).JQuery.Attr.RemoveClass(B.Active);
              dsl.Self().JQuery.Attr.AddClass(B.Active);
          })
          .AsHtmlAttributes(new { @class = @class, href = "#" + value })
          .ToLink(name))
}

@{
    using (var template = Html.Incoding().Template<OptGroupVm>())
    {
        using (var each = template.ForEach())
        {
            <li class="expanded">
                @Link(each.For(s => s.Title), each.For(s => s.Title), "sidebar-nav-item expandable")
                <ul class="sidebar-nav-items loaded" style="height: auto">
                    @using (var innerEach = each.ForEach(s => s.Items))
{
                        <li>
                            @innerEach.IsInline(r => r.CssClass,@<text>
                                                                    @(Html.When(JqueryBind.KeyPress | JqueryBind.FocusOut)
                                                                          .Ajax(new MessageCommand.JoinToGroupCommand()
                                                                          {
                                                                              MessageId = innerEach.For(s => s.CssClass),
                                                                              Group = Selector.Jquery.Self()
                                                                          })
                                                                          .OnBegin(dsl =>
                                                                          {
                                                                              dsl.Break.If(() => Selector.Jquery.Self().HasClass(B.Hidden));
                                                                              dsl.Break.If(() => Selector.Event.Which != 13 && Selector.Event.Type == JqueryBind.KeyPress.ToJqueryString());
                                                                          })
                                                                          .OnSuccess(dsl => { dsl.WithId(typeof(GetMessagesQuery.AsNav).Name).Trigger.None(); })
                                                                          .AsHtmlAttributes(new { @class = B.Hidden.ToLocalization(), placeholder = "Enter group",style= "width: 225px;margin-left:21px;" })
                                                                          .ToInput(HtmlInputType.Text, ""))
                                                                    @(Html.When(JqueryBind.Click)
                                                                          .OnSuccess(dsl =>
                                                                                     {
                                                                                         dsl.WithSelf(s => s.Closest(HtmlTag.Li).Find(HtmlTag.Input)).JQuery.Attr.ToggleClass(B.Hidden);
                                                                                         dsl.Self().JQuery.Attr.ToggleClass(B.Hidden);
                                                                                     })
                                                                          .AsHtmlAttributes(new { @class = "glyphicon glyphicon-pushpin " + B.Hidden.ToLocalization(), style = "top: 24px;left: 17px; " })
                                                                          .ToI())
                                                                 </text>)
                            @Link(innerEach.For(s => s.Text), innerEach.For(s => s.Value), "sidebar-nav-item")
                        </li>
                    }
                </ul>
            </li>
        }
    }
}

src/MvdEndPoint.UI/Views/Endpoint/Sandbox_Item_Tmpl.cshtml
@{
    using (var template = Html.Incoding().Template<GetMessageDetailQuery.Response>())
    {
        using (var each = template.ForEach())
        {
            <div class="form-group">
                @using (each.Is(r => r.IsBool))
                {
                    <div class="col-xs-offset-2 col-xs-10">
                        <div class="checkbox">
                            <label>
                                @Html.CheckBox(each.For(r => r.Name)) @each.For(r => r.Name)
                            </label>
                        </div>
                    </div>
                }
                @using (each.Not(s => s.IsBool))
                {
                    <label class="control-label col-xs-2" for="@each.For(r => r.Name)">
                        @each.For(r => r.Name)
                    </label>
                    <div class="col-xs-9">
                        @using (each.Is(r => r.IsFile))
                        {
                            <input type="file" name="@each.For(s => s.Name)"/>
                        }
                        @using (each.Is(r => r.IsEnum))
                        {
                            @Html.DropDownList(each.For(r => r.Name), new SelectList(new string[0]), Html.When(JqueryBind.InitIncoding)
                                                                                                         .Ajax(new GetEnumForDD { TypeId = each.For(r => r.GUID) })
                                                                                                         .OnSuccess(dsl => dsl.Self().Insert.WithTemplate(IncodingHtmlHelper.DropDownTemplateId).Html())
                                                                                                         .AsHtmlAttributes(new {@class= "form-control" }))
                        }
                        @using (each.Is(r => r.IsString))
                        {
                            @Html.TextBox(each.For(r => r.Name), "", new { @class = "form-control" })
                        }
                        @using (each.Is(r => r.IsDate))
                        {
                            @Html.TextBox(each.For(r => r.Name), "", new { @class = "form-control" })
                        }
                        @using (each.Is(r => r.IsNumber))
                        {
                            @Html.TextBox(each.For(r => r.Name), "", new { @class = "form-control" })
                        }
                        @Html.ValidationMessage(each.For(r => r.Name))
                    </div>
                }

            </div>
        }
    }
}

src/MvdEndPoint.UI/Views/Home/Ajax_Response_Tmpl.cshtml
@using Incoding.MvcContrib
@using MvdEndPoint.UI.Models
@{
    using (var template = Html.Incoding().Template<IncAjaxEventVm>())
    {
        using (var each = template.ForEach())
        {
            <div>
                <label>Status Code:@each.For(r => r.StatusCode)</label>
                <label>Status Text:@each.For(r => r.StatusText)</label>                  
            </div>
            <div>
                @each.ForRaw(r => r.ResponseText)
            </div>
        }
    }

}

src/MvdEndPoint.UI/Views/Home/Endpoint_Item_Tmpl.cshtml
@using Incoding.Extensions
@using Incoding.MetaLanguageContrib
@using Incoding.MvcContrib
@using MvdEndPoint.Domain
@using MvdEndPoint.UI.Controllers
@model MvdEndPoint.UI.Controllers.EndPointItem.Tmpl
@{
    using (var template = Html.Incoding().Template<EndPointItem>())
    {
        string dialogId = Guid.NewGuid().ToString();

        <div id="@dialogId"></div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        @(Html.When(JqueryBind.Click)
                              .Direct()
                              .OnSuccess(dsl =>
                                             {
                                                 dsl.WithName(Model.CheckedTypeName)
                                                    .Behaviors(inDsl =>
                                                                   {
                                                                       inDsl.Core().JQuery.Attributes.RemoveAttr(HtmlAttribute.Checked);
                                                                       inDsl.Core().JQuery.Attributes.SetAttr(HtmlAttribute.Checked).If(() => Selector.Jquery.Self());
                                                                   });
                                                 dsl.WithName(Model.AllId).Core().Trigger.Invoke(JqueryBind.InitIncoding);
                                             })
                              .AsHtmlAttributes()
                              .ToCheckBox(false))
                    </th>       
                    <th>Name</th>
                    <th>Url</th>
                    <th>Type</th>
                    <th>Result</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @using (var each = template.ForEach())
                {
                    string trId = "tr" + each.For(r => r.Name);
                    <tr>
                        <td>
                            @(Html.When(JqueryBind.Change)
                                  .Direct()
                                  .OnSuccess(dsl => dsl.WithId(Model.AllId).Core().Trigger.Invoke(JqueryBind.InitIncoding))
                                  .AsHtmlAttributes(new { name = Model.CheckedTypeName, value = each.For(r => r.AssemblyQualifiedName) })
                                  .ToCheckBox(false))
                        </td>
                        @*     <td>
                            @(Html.When(JqueryBind.Click)
                                  .Direct()
                                  .OnSuccess(dsl =>
                                                 {
                                                     dsl.WithId(trId).Core().JQuery.Attributes.ToggleClass("hide");
                                                     dsl.Self().Core().JQuery.Attributes.ToggleClass("icon-plus icon-minus");
                                                 })
                                  .AsHtmlAttributes(new { @class = "icon icon-plus" })
                                  .ToI())
                        </td>*@
                        <td>@each.For(r => r.Name)</td>
                        <td>
                            <a href="@each.For(r => r.Url)">
                                @each.For(r => r.Url)
                            </a>
                        </td>
                        <td>@each.For(r => r.Type)</td>
                        <td></td>
                        <td>
                            @(Html.When(JqueryBind.Click)
                                  .AjaxGet(Url.Action("Endpoint", "Dispatcher", new { id = each.For(r => r.GUID) }))
                                  .OnSuccess(dsl => dsl.WithId(dialogId).Behaviors(inDsl =>
                                                                                       {
                                                                                           string urlSandbox = Url.Dispatcher().AsView("~/Views/Home/Sandbox_Item_Tmpl.cshtml");
                                                                                           inDsl.Core().Insert.WithTemplateByUrl(urlSandbox).Html();
                                                                                           inDsl.JqueryUI().Dialog.Open(options =>
                                                                                                                            {
                                                                                                                                options.Title = "Sandbox";
                                                                                                                                options.Width = "500px;";
                                                                                                                            });
                                                                                       }))
                                  .AsHtmlAttributes(new { @class = "btn btn-primary" })
                                  .ToButton("Sandbox")) 
                            
                            
                            @(Html.When(JqueryBind.InitIncoding)
                                  .Direct()
                                  .OnSuccess(dsl =>
                                                 {
                                                     var url = Url.Dispatcher().Query<MessagesToPackageQuery>(new
                                                                                                                  {
                                                                                                                          Names = each.For(r => r.AssemblyQualifiedName),
                                                                                                                          BaseUrl = Selector.Jquery.Name(Model.BaseUrlName),
                                                                                                                          Device = Model.DeviceName.ToName()
                                                                                                                  })
                                                                  .AsFile(incFileDownloadName: each.For(r => r.Name) + ".zip")
                                                                  .ToBuildUrl();
                                                     dsl.Self().Core().JQuery.Attributes.SetAttr(HtmlAttribute.Href, url);
                                                 })
                                  .AsHtmlAttributes(new { name = Model.DownloadLinkName })
                                  .ToLink("Download"))                                                              
                        </td>
                    </tr>
                    <tr id="@trId" class="hide">
                        <td colspan="5">
                            <table class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Type</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @using (var innerEach = each.ForEach(r => r.Properties))
                                    {
                                        <tr>
                                            <td>@innerEach.For(r => r.Name)</td>
                                            <td>@innerEach.For(r => r.Type)</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
}

src/MvdEndPoint.UI/Views/Home/Index.cshtml
@using Incoding.MvcContrib
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@(Html.When(JqueryBind.Click)
      .Do()
      .Direct()
      .OnSuccess(dsl => dsl.Utilities.Window.Alert("Hello Incoding framework"))
      .AsHtmlAttributes()
      .ToButton("Click ME"))

src/MvdEndPoint.UI/Views/Home/Sandbox_Item_Tmpl.cshtml
@using Incoding.MvcContrib
@using MvdEndPoint.UI.Controllers
@model EndPointItem

@{
    using (var template = Html.Incoding().Template<EndPointItem>())
    {
        string resultId = Guid.NewGuid().ToString();
        using (var each = template.ForEach())
        {
            using (Html.When(JqueryBind.IncAjaxError)
                       .Do()
                       .Event()
                       .OnSuccess(dsl => dsl.WithId(resultId).Core().Insert.WithTemplateByUrl(this.Url.Dispatcher().AsView("~/Views/Home/Ajax_Response_Tmpl.cshtml")).Html())
                       .When(JqueryBind.Submit)
                       .DoWithPreventDefault()
                       .Submit()
                       .OnSuccess(dsl => dsl.WithId(resultId).Core().Eval("DataToString(this.target,data)"))
                       .OnError(dsl => dsl.WithId(resultId).Core().Insert.WithTemplateByUrl(Url.Dispatcher().AsView("~/Views/Home/ModelState_Tmpl.cshtml")).Html())
                       .AsHtmlAttributes(new { action = each.For(r => r.Url), method = HttpVerbs.Post, @class = "form-horizontal" })
                       .ToBeginTag(Html, HtmlTag.Form))
            {
                <div class="control-group">
                    <label class="control-label">Name:</label>
                    <div class="controls">@each.For(r => r.Name)</div>
                </div>
                using (var innerEach = each.ForEach(r => r.Properties))
                {
                    <div class="control-group">
                        @Html.Label(innerEach.For(r => r.Name), new { @class = "control-label" })
                        <div class="controls">
                            @using (innerEach.Is(r => r.IsBool))
                            {
                                @Html.CheckBox(innerEach.For(r => r.Name))
                            }
                            
                            @using (innerEach.Is(r => r.IsEnum))
                            {
                                @Html.DropDownList(innerEach.For(r => r.Name), new SelectList(new string[0]), Html.When(JqueryBind.InitIncoding)
                                                                                                                  .Do()
                                                                                                                  .AjaxGet(Url.Action("FetchEnum", "Dispatcher", new { TypeId = innerEach.For(r => r.TypeId) }))
                                                                                                                  .OnSuccess(dsl => dsl.Self().Core().Insert.WithTemplateById(IncodingHtmlHelper.DropDownTemplateId).Html())
                                                                                                                  .AsHtmlAttributes())
                            }
                            

                            @using (innerEach.Is(r => r.IsSimple))
                            {
                                @Html.TextBox(innerEach.For(r => r.Name))
                            }
                        </div>
                    </div>
                }         
                <div class="form-actions">
                    <input type="submit" value="Run" class="btn btn-success"/>
                </div>
            }
        }

        <div id="@resultId"></div>
    }

}

src/MvdEndPoint.UI/Views/Shared/_Layout.cshtml
@using Incoding.MvcContrib
<!DOCTYPE html>
<html >
    <head>                 
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.10.0.min.js")"> </script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/underscore.min.js")"> </script>                
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.form.min.js")"> </script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.history.js")"> </script>        
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.min.js")"> </script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"> </script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/handlebars.min.js")"> </script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/incoding.framework.js")"> </script>                      
        <script>
            TemplateFactory.Version = '@Guid.NewGuid().ToString()';
        </script>
    </head>
    @Html.Incoding().RenderDropDownTemplate()
    <body>        
        @RenderBody()
    </body>
</html>